### ISSUE TITLE
chili_pdf crashes on 1.9.2

### ISSUE THREAD

**Issue by makheshwar** [tomkersten/chili_pdf#19]
Recently while upgrading to 1.9.2, the test case for downloading a wiki page as pdf failed with the following stack trace

Seems something wrong with the lambda change in 1.9.2, but could not figure out completly.

wrong number of arguments (1 for 0)
/usr/local/share/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chili_pdf-0.4.4/lib/chili_pdf/token_manager.rb:12:in `block in <module:TokenManager>'
/usr/local/share/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chili_pdf-0.4.4/lib/chili_pdf/string_token.rb:66:in`call'
/usr/local/share/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chili_pdf-0.4.4/lib/chili_pdf/string_token.rb:66:in `replacement_value'
/usr/local/share/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chili_pdf-0.4.4/lib/chili_pdf/string_token.rb:54:in`apply_to'
/usr/local/share/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chili_pdf-0.4.4/lib/chili_pdf/token_manager.rb:32:in `block in apply_tokens_to'
/usr/local/share/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chili_pdf-0.4.4/lib/chili_pdf/token_manager.rb:32:in`each'
/usr/local/share/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chili_pdf-0.4.4/lib/chili_pdf/token_manager.rb:32:in `inject'
/usr/local/share/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chili_pdf-0.4.4/lib/chili_pdf/token_manager.rb:32:in`apply_tokens_to'
/usr/local/share/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chili_pdf-0.4.4/lib/chili_pdf/formatter.rb:75:in `replace_tokens_in'
/usr/local/share/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chili_pdf-0.4.4/lib/chili_pdf/formatter.rb:70:in`block in substitute_tokens'
/usr/local/share/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chili_pdf-0.4.4/lib/chili_pdf/formatter.rb:68:in `each'
/usr/local/share/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chili_pdf-0.4.4/lib/chili_pdf/formatter.rb:68:in`inject'
/usr/local/share/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chili_pdf-0.4.4/lib/chili_pdf/formatter.rb:68:in `substitute_tokens'
/usr/local/share/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chili_pdf-0.4.4/lib/chili_pdf/formatter.rb:56:in`footer_options'
/usr/local/share/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chili_pdf-0.4.4/lib/chili_pdf/formatter.rb:45:in `render_options'
/usr/local/share/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chili_pdf-0.4.4/app/controllers/extended_wiki_controller.rb:10:in`block (2 levels) in show'
/usr/local/share/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/actionpack-2.3.14/lib/action_controller/mime_responds.rb:135:in `call'
/usr/local/share/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/actionpack-2.3.14/lib/action_controller/mime_responds.rb:135:in`block in custom'
/usr/local/share/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/actionpack-2.3.14/lib/action_controller/mime_responds.rb:179:in `call'
/usr/local/share/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/actionpack-2.3.14/lib/action_controller/mime_responds.rb:179:in`block in respond'
/usr/local/share/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/actionpack-2.3.14/lib/action_controller/mime_responds.rb:173:in `each'
/usr/local/share/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/actionpack-2.3.14/lib/action_controller/mime_responds.rb:173:in`respond'
/usr/local/share/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/actionpack-2.3.14/lib/action_controller/mime_responds.rb:107:in `respond_to'
/usr/local/share/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chili_pdf-0.4.4/app/controllers/extended_wiki_controller.rb:9:in`show'
/usr/local/share/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/actionpack-2.3.14/lib/action_controller/base.rb:1333:in `perform_action'
/usr/local/share/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/actionpack-2.3.14/lib/action_controller/filters.rb:617:in`call_filters'
/usr/local/share/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/actionpack-2.3.14/lib/action_controller/filters.rb:610:in `perform_action_with_filters'
/usr/local/share/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/actionpack-2.3.14/lib/action_controller/benchmarking.rb:68:in`block in perform_action_with_benchmark'
/usr/local/share/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/activesupport-2.3.14/lib/active_support/core_ext/benchmark.rb:17:in `block in ms'
/usr/local/share/rbenv/versions/1.9.2-p290/lib/ruby/1.9.1/benchmark.rb:310:in`realtime'
/usr/local/share/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/activesupport-2.3.14/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/usr/local/share/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/actionpack-2.3.14/lib/action_controller/benchmarking.rb:68:in`perform_action_with_benchmark'
/usr/local/share/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/actionpack-2.3.14/lib/action_controller/rescue.rb:160:in `perform_action_with_rescue'
/usr/local/share/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/actionpack-2.3.14/lib/action_controller/flash.rb:151:in`perform_action_with_flash'
/usr/local/share/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/actionpack-2.3.14/lib/action_controller/base.rb:532:in `process'
/usr/local/share/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/actionpack-2.3.14/lib/action_controller/filters.rb:606:in`process_with_filters'
/usr/local/share/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/actionpack-2.3.14/lib/action_controller/base.rb:391:in `process'
/usr/local/share/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/actionpack-2.3.14/lib/action_controller/base.rb:386:in`call'
/usr/local/share/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/actionpack-2.3.14/lib/action_controller/routing/route_set.rb:438:in `call'

**Comment by makheshwar** [comment]
The issue is with the datestamp.  Temporarily you can fix by removing the {{datestamp}} from footer and header and also disable footer and header.  The code snippet to reproduce from the ruby console is 

ChiliPDF::TokenManager.tokens
a = ChiliPDF::TokenManager.tokens.first
a.apply_to "123"   #this shall succeed
a = ChiliPDF::TokenManager.tokens[2]
a.apply_to Time.now.strftime('%d-%b-%Y')   #this shall fail with the above error message.

**Comment by waleedjaffar** [comment]
This issue can be temporarily solved by following below steps.

1) Navigate to Admin - Plugins 
2) Click on configure next to Chili PDF Plugin.
3) Under Typical tab, uncheck Display Page Header and Display Page Footer. 
4) Click on Apply, Navigate to wiki page of a project and export. 
5) PDF is generated as desired.

This solution was given to me by Makheshwar. :). 
Need permanent solution to this problem.
